spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: shadow0207

