spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    datasource:
        driverClassName: org.postgresql.Driver
        url:   jdbc:postgresql://n-n-nagaoka.herokuapp.com:5432/d90jfae484s31
        user: kvxhdubezhyppe
        password: c4fshNaNCTcB_x0sMOY8lx5HJx
#        url: https://git.heroku.com/n-n-nico-calender.git
#        url: jdbc:postgresql://localhost:5432/postgres

#        username: mchilqfhaemquu
#        password: th3ZJJznCl8g_z3HMKwqcymHND
#        username: postgres
#        password: shadow0207
#      driverClassName: org.h2.Driver
#              url: jdbc:h2:file:./db/test
#              username: sa
#              password: