spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    datasource:
        driverClassName: org.postgresql.Driver
        url:   jdbc:postgresql://n-n-nico-calender.herokuapp.com request_id=39d4bdeb-3c8e-4738-a6e5-43d62df7ae8b:5432/
        user: sjuygvwfpujnme
        password: -Pqts-t003U04yjLSB3x-c8fLR
#        url: https://git.heroku.com/n-n-nico-calender.git
#        url: jdbc:postgresql://localhost:5432/postgres

#        username: mchilqfhaemquu
#        password: th3ZJJznCl8g_z3HMKwqcymHND
#        username: postgres
#        password: shadow0207
#      driverClassName: org.h2.Driver
#              url: jdbc:h2:file:./db/test
#              username: sa
#              password: