spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    datasource:
        driverClassName: org.postgresql.Driver
        url:   jdbc:postgres://@ec2-54-243-224-151.compute-1.amazonaws.com:5432/dcercsd241nddr
        user: sjuygvwfpujnme
        password: -Pqts-t003U04yjLSB3x-c8fLR
#        url: https://git.heroku.com/n-n-nico-calender.git
#        url: jdbc:postgresql://localhost:5432/postgres

#        username: mchilqfhaemquu
#        password: th3ZJJznCl8g_z3HMKwqcymHND
#        username: postgres
#        password: shadow0207
#      driverClassName: org.h2.Driver
#              url: jdbc:h2:file:./db/test
#              username: sa
#              password: