spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./db/test
        username: 
        password:
spring1:
        datasource:
        driverClassName: postgresql.Driver
        url: jdbc:h2:file:./db/test